package container

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

type BuildInput struct {
	ContextDir string
	Tag        string
	User       HostUser
}

func Build(input BuildInput) error {
	if input.Tag == "" {
		input.Tag = "claude-env:custom"
	}
	if input.ContextDir == "" {
		pwd, _ := os.Getwd()
		input.ContextDir = filepath.Join(pwd, ".container-sandbox")
	}
	if input.User.Username == "" {
		input.User = DetectHostUser()
	}

	cmd := exec.Command("docker", "build",
		"-t", input.Tag,
		"--build-arg", fmt.Sprintf("USERNAME=%s", input.User.Username),
		"--build-arg", fmt.Sprintf("USER_UID=%d", input.User.UID),
		"--build-arg", fmt.Sprintf("USER_GID=%d", input.User.GID),
		"-f", filepath.Join(input.ContextDir, "Dockerfile"),
		input.ContextDir,
	)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

type LaunchScriptInput struct {
	Name       string
	Mode       Mode
	Components []Component
	User       HostUser
}

func GenerateLaunchScript(input LaunchScriptInput) (string, error) {
	if input.User.Username == "" {
		input.User = DetectHostUser()
	}
	dir := filepath.Join(os.Getenv("HOME"), ".config", "captain")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", fmt.Errorf("creating config dir: %w", err)
	}
	path := filepath.Join(dir, fmt.Sprintf("claude-%s.sh", input.Name))
	tag := fmt.Sprintf("claude-env:%s", input.Name)

	var volumeLines string
	if input.Mode == ModeMount {
		volumeLines = buildVolumeMounts(input.Components, input.User)
	}

	content := fmt.Sprintf(`#!/bin/bash
# Launch script for claude-env:%s (%s mode)
# Generated by captain container
docker run -it --rm \
  -e ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY}" \
  -w "$PWD" \
  -v "$PWD:$PWD" \
%s  %s "$@"
`, input.Name, input.Mode, volumeLines, tag)

	if err := os.WriteFile(path, []byte(content), 0o755); err != nil {
		return "", fmt.Errorf("writing launch script: %w", err)
	}
	return path, nil
}

func buildVolumeMounts(components []Component, user HostUser) string {
	home := user.ContainerHome()
	var lines []string
	for _, c := range components {
		if !c.Selected {
			continue
		}
		if c.ContentKey != "" {
			if c.GitRoot != "" {
				basename := filepath.Base(c.GitRoot)
				lines = append(lines, fmt.Sprintf("  -v %q:%q \\", c.GitRoot, "/workspace/"+basename))
			}
			if c.ProjectPath != "" {
				encoded := filepath.Base(c.ProjectPath)
				lines = append(lines, fmt.Sprintf("  -v %q:%q:ro \\", c.ProjectPath, home+"/.claude/projects/"+encoded))
			}
			continue
		}
		src := c.SourcePath
		target := c.TargetPath
		if c.IsDir {
			src += "/"
			target += "/"
		}
		lines = append(lines, fmt.Sprintf("  -v %q:%q:ro \\", src, target))
	}
	if len(lines) == 0 {
		return ""
	}
	return strings.Join(lines, "\n") + "\n"
}

func PrintBuildInstructions(tag string, mode Mode, scriptPath string) {
	fmt.Println()
	fmt.Println("Build complete!")
	fmt.Println()
	fmt.Printf("  Image: %s\n", tag)
	fmt.Println()
	fmt.Println("Usage:")
	if scriptPath != "" {
		fmt.Printf("  %s\n", scriptPath)
	}
	fmt.Println()
	fmt.Println("  # Or run directly:")
	fmt.Printf("  docker run -it --rm \\\n")
	fmt.Printf("    -e ANTHROPIC_API_KEY=\"${ANTHROPIC_API_KEY}\" \\\n")
	fmt.Printf("    -w \"$PWD\" -v \"$PWD:$PWD\" \\\n")
	fmt.Printf("    %s\n", tag)
	fmt.Println()
	if mode == ModeMount {
		fmt.Println("  Note: mount mode — config is bind-mounted via the launch script")
	}
}
