package container

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

const dockerfileUserBlock = `
ARG USERNAME={{.Username}}
ARG USER_UID={{.UID}}
ARG USER_GID={{.GID}}

# Create user/group matching host
RUN if ! getent group ${USER_GID} > /dev/null 2>&1; then groupadd -g ${USER_GID} ${USERNAME}; fi && \
  if ! id -u ${USERNAME} > /dev/null 2>&1; then useradd -u ${USER_UID} -g ${USER_GID} -m -s /bin/bash ${USERNAME}; fi && \
  mkdir -p {{.HomeDir}}/.claude && \
  chown -R ${USERNAME}:${USER_GID} {{.HomeDir}}
`

const dockerfileClaudeInstall = `
# Install/update Claude Code CLI
RUN npm install -g @anthropic-ai/claude-code@latest
`

const dockerfileInstallBlocks = `
{{- range .InstallBlocks}}
RUN {{.}}
{{- end}}`

const dockerfileCopyTemplate = `# Auto-generated by captain container — profile: {{.Name}} (copy mode)
FROM {{.BaseImage}}

USER root
` + dockerfileUserBlock + dockerfileClaudeInstall + dockerfileInstallBlocks + `
{{- range .CopyBlocks}}

# {{.Comment}}
{{.Instruction}}
{{- end}}

{{- if .HookFiles}}

# Make hooks executable
RUN chmod +x {{range .HookFiles}}{{$.HomeDir}}/.claude/hooks/{{.}} {{end}}
{{- end}}

# Fix permissions
RUN chown -R {{.UID}}:{{.GID}} {{.HomeDir}}/.claude {{if .HasDotfiles}}{{.HomeDir}}/.dotfiles{{end}}

USER root
`

const dockerfileMountTemplate = `# Auto-generated by captain container — profile: {{.Name}} (mount mode)
# Config is bind-mounted at runtime via the launch script
FROM {{.BaseImage}}

USER root
` + dockerfileUserBlock + dockerfileClaudeInstall + dockerfileInstallBlocks + `
# Create mount-point directories
RUN mkdir -p {{.HomeDir}}/.claude/agents \
             {{.HomeDir}}/.claude/commands \
             {{.HomeDir}}/.claude/hooks \
             {{.HomeDir}}/.claude/plugins \
             {{.HomeDir}}/.claude/skills \
             {{.HomeDir}}/.claude/mcp \
  && chown -R {{.UID}}:{{.GID}} {{.HomeDir}}/.claude

USER root
`

type GenerateInput struct {
	Name          string
	BaseImage     string
	Mode          Mode
	Components    []Component
	OutputDir     string
	User          HostUser
	Patches       []Patch
	PresetInstall []string
}

type templateData struct {
	Name          string
	BaseImage     string
	Username      string
	UID           int
	GID           int
	HomeDir       string
	CopyBlocks    []copyBlock
	HookFiles     []string
	HasDotfiles   bool
	InstallBlocks []string
}

type copyBlock struct {
	Comment     string
	Instruction string
}

func Generate(input GenerateInput) (string, error) {
	if input.OutputDir == "" {
		pwd, err := os.Getwd()
		if err != nil {
			return "", fmt.Errorf("getting working directory: %w", err)
		}
		input.OutputDir = pwd
	}
	if input.BaseImage == "" {
		input.BaseImage = "claude-env:base"
	}
	if input.Mode == "" {
		input.Mode = ModeCopy
	}
	if input.User.Username == "" {
		input.User = DetectHostUser()
	}

	selected := FilterSelected(input.Components)
	if len(selected) == 0 {
		return "", fmt.Errorf("no components selected")
	}

	if input.Mode == ModeMount {
		return generateMount(input, selected)
	}
	return generateCopy(input, selected)
}

func generateCopy(input GenerateInput, selected []Component) (string, error) {
	contextDir := filepath.Join(input.OutputDir, ".container-sandbox")
	if err := os.RemoveAll(contextDir); err != nil {
		return "", fmt.Errorf("cleaning build context: %w", err)
	}
	if err := os.MkdirAll(contextDir, 0o755); err != nil {
		return "", fmt.Errorf("creating build context: %w", err)
	}
	_ = os.WriteFile(filepath.Join(contextDir, ".gitignore"), []byte("*\n"), 0o644)

	data := templateData{
		Name:          input.Name,
		BaseImage:     input.BaseImage,
		Username:      input.User.Username,
		UID:           input.User.UID,
		GID:           input.User.GID,
		HomeDir:       input.User.ContainerHome(),
		InstallBlocks: input.PresetInstall,
	}

	grouped := GroupByCategory(selected)
	for _, cat := range AllCategories {
		items, ok := grouped[cat]
		if !ok {
			continue
		}
		var fileItems []Component
		for _, item := range items {
			if item.ContentKey != "" {
				continue
			}
			fileItems = append(fileItems, item)
		}
		if len(fileItems) > 0 {
			blocks, hookFiles, hasDotfiles, err := stageCategoryFiles(contextDir, cat, fileItems)
			if err != nil {
				return "", fmt.Errorf("staging %s: %w", cat, err)
			}
			data.CopyBlocks = append(data.CopyBlocks, blocks...)
			data.HookFiles = append(data.HookFiles, hookFiles...)
			if hasDotfiles {
				data.HasDotfiles = true
			}
		}
	}

	homeDir := input.User.ContainerHome()
	settingsPath := filepath.Join(input.User.HomeDir, ".claude", "settings.json")
	if _, err := os.Stat(settingsPath); err == nil {
		block, err := stageSettingsJSON(contextDir, settingsPath, input.Components, homeDir+"/.claude/settings.json")
		if err != nil {
			return "", fmt.Errorf("staging settings.json: %w", err)
		}
		data.CopyBlocks = append(data.CopyBlocks, block)
	}

	claudeJSON := filepath.Join(input.User.HomeDir, ".claude.json")
	if _, err := os.Stat(claudeJSON); err == nil {
		block, err := stageClaudeJSON(contextDir, claudeJSON, input.Components, homeDir+"/.claude.json")
		if err != nil {
			return "", fmt.Errorf("staging .claude.json: %w", err)
		}
		data.CopyBlocks = append(data.CopyBlocks, block)
	}

	if len(input.Patches) > 0 {
		if err := applyPatches(contextDir, input.Patches); err != nil {
			return "", fmt.Errorf("applying patches: %w", err)
		}
	}

	if _, err := renderDockerfile(contextDir, dockerfileCopyTemplate, data); err != nil {
		return "", err
	}
	return contextDir, nil
}

func generateMount(input GenerateInput, _ []Component) (string, error) {
	contextDir := filepath.Join(input.OutputDir, ".container-sandbox")
	if err := os.MkdirAll(contextDir, 0o755); err != nil {
		return "", fmt.Errorf("creating context dir: %w", err)
	}
	_ = os.WriteFile(filepath.Join(contextDir, ".gitignore"), []byte("*\n"), 0o644)

	data := templateData{
		Name:          input.Name,
		BaseImage:     input.BaseImage,
		Username:      input.User.Username,
		UID:           input.User.UID,
		GID:           input.User.GID,
		HomeDir:       input.User.ContainerHome(),
		InstallBlocks: input.PresetInstall,
	}
	if _, err := renderDockerfile(contextDir, dockerfileMountTemplate, data); err != nil {
		return "", err
	}
	return contextDir, nil
}

func renderDockerfile(contextDir, tmplStr string, data templateData) (string, error) {
	tmpl, err := template.New("dockerfile").Parse(tmplStr)
	if err != nil {
		return "", fmt.Errorf("parsing template: %w", err)
	}

	dockerfilePath := filepath.Join(contextDir, "Dockerfile")
	f, err := os.Create(dockerfilePath)
	if err != nil {
		return "", fmt.Errorf("creating dockerfile: %w", err)
	}
	defer f.Close() //nolint:errcheck

	if err := tmpl.Execute(f, data); err != nil {
		return "", fmt.Errorf("executing template: %w", err)
	}
	return dockerfilePath, nil
}

func stageCategoryFiles(contextDir string, cat Category, items []Component) ([]copyBlock, []string, bool, error) {
	var blocks []copyBlock
	var hookFiles []string
	hasDotfiles := false

	for _, item := range items {
		relPath := filepath.Join(string(cat), item.Name)
		destInContext := filepath.Join(contextDir, relPath)

		if err := os.MkdirAll(filepath.Dir(destInContext), 0o755); err != nil {
			return nil, nil, false, err
		}

		if item.IsDir {
			if err := copyDir(item.SourcePath, destInContext); err != nil {
				return nil, nil, false, fmt.Errorf("copying dir %s: %w", item.Name, err)
			}
		} else {
			if err := copyFile(item.SourcePath, destInContext); err != nil {
				return nil, nil, false, fmt.Errorf("copying file %s: %w", item.Name, err)
			}
		}

		blocks = append(blocks, copyBlock{
			Comment:     fmt.Sprintf("%s: %s", cat, item.Name),
			Instruction: fmt.Sprintf("COPY %s %s", relPath, item.TargetPath),
		})

		if cat == CategoryHooks {
			hookFiles = append(hookFiles, item.Name)
		}
		if strings.Contains(item.TargetPath, ".dotfiles") {
			hasDotfiles = true
		}
	}
	return blocks, hookFiles, hasDotfiles, nil
}

func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close() //nolint:errcheck

	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close() //nolint:errcheck

	_, err = io.Copy(out, in)
	return err
}

func copyDir(src, dst string) error {
	return filepath.Walk(src, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(src, path)
		target := filepath.Join(dst, rel)
		if info.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		return copyFile(path, target)
	})
}
