version: "3"

vars:
  BINARY: captain
  BIN_DIR: .bin
  INSTALL_DIR: /usr/local/bin

tasks:
  default:
    cmds:
      - task --list

  build:
    desc: Build the captain binary
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -o {{.BIN_DIR}}/{{.BINARY}} ./cmd/captain

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run ./...

  test:
    desc: Run tests
    cmds:
      - go test ./...

  test:verbose:
    desc: Run tests with verbose output
    cmds:
      - go test -v ./...

  install:
    desc: Build and install captain to /usr/local/bin
    deps: [build]
    cmds:
      - cp {{.BIN_DIR}}/{{.BINARY}} {{.INSTALL_DIR}}/{{.BINARY}}

  fmt:
    desc: Format Go code
    cmds:
      - gofmt -w .

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.BIN_DIR}}

  all:
    desc: Run fmt, lint, test, and build
    cmds:
      - task: fmt
      - task: lint
      - task: test
      - task: build
