// Code generated by pkg/ai/internal/gen-model-registry; DO NOT EDIT.

package ai

var exactModelRegistry = []registryModel{
	{ID: "claude-sonnet-5", Provider: modelProviderAnthropic, Family: "sonnet", Version: "5", Label: "Claude Sonnet 5", ReleaseDate: "2026-06-29", Reasoning: true, ContextWindow: 1000000, Preferred: true},
	{ID: "claude-fable-5", Provider: modelProviderAnthropic, Family: "fable", Version: "5", Label: "Claude Fable 5", ReleaseDate: "2026-06-07", Reasoning: true, ContextWindow: 1000000, Preferred: true},
	{ID: "claude-opus-4-8", Provider: modelProviderAnthropic, Family: "opus", Version: "4.8", Label: "Claude Opus 4.8", ReleaseDate: "2026-05-28", Reasoning: true, ContextWindow: 1000000, Preferred: true},
	{ID: "claude-opus-4-7", Provider: modelProviderAnthropic, Family: "opus", Version: "4.7", Label: "Claude Opus 4.7", ReleaseDate: "2026-04-14", Reasoning: true, ContextWindow: 1000000, Preferred: true},
	{ID: "claude-sonnet-4-6", Provider: modelProviderAnthropic, Family: "sonnet", Version: "4.6", Label: "Claude Sonnet 4.6", ReleaseDate: "2026-02-17", Reasoning: true, ContextWindow: 1000000, Preferred: true},
	{ID: "claude-haiku-4-5", Provider: modelProviderAnthropic, Family: "haiku", Version: "4.5", Label: "Claude Haiku 4.5", ReleaseDate: "2025-10-15", Reasoning: true, ContextWindow: 200000, Preferred: true},
	{ID: "claude-haiku-4-5-20251001", Provider: modelProviderAnthropic, Family: "haiku", Version: "4.5-20251001", Label: "Claude Haiku 4.5", ReleaseDate: "2025-10-15", Reasoning: true, ContextWindow: 200000},

	{ID: "gpt-5.5", Provider: modelProviderOpenAI, Family: "gpt", Version: "5.5", Label: "GPT-5.5", ReleaseDate: "2026-04-23", Reasoning: true, ContextWindow: 1050000, Preferred: true},
	{ID: "gpt-5.4", Provider: modelProviderOpenAI, Family: "gpt", Version: "5.4", Label: "GPT-5.4", ReleaseDate: "2026-03-05", Reasoning: true, ContextWindow: 1050000, Preferred: true},
	{ID: "gpt-5", Provider: modelProviderOpenAI, Family: "gpt", Version: "5", Label: "GPT-5", ReleaseDate: "2025-08-07", Reasoning: true, ContextWindow: 400000, Preferred: true},

	{ID: "gemini-3.5-flash", Provider: modelProviderGoogle, Family: "gemini", Version: "3.5-flash", Label: "Gemini 3.5 Flash", ReleaseDate: "2026-05-19", Reasoning: true, ContextWindow: 1048576, Preferred: true},
	{ID: "gemini-2.5-pro", Provider: modelProviderGoogle, Family: "gemini", Version: "2.5-pro", Label: "Gemini 2.5 Pro", ReleaseDate: "2025-06-17", Reasoning: true, ContextWindow: 1048576, Preferred: true},
	{ID: "gemini-2.5-flash", Provider: modelProviderGoogle, Family: "gemini", Version: "2.5-flash", Label: "Gemini 2.5 Flash", ReleaseDate: "2025-06-17", Reasoning: true, ContextWindow: 1048576, Preferred: true},

	{ID: "deepseek-v4-pro", Provider: modelProviderDeepSeek, Family: "deepseek", Version: "v4-pro", Label: "DeepSeek V4 Pro", ReleaseDate: "2026-04-24", Reasoning: true, ContextWindow: 1000000, Preferred: true},
	{ID: "deepseek-v4-flash", Provider: modelProviderDeepSeek, Family: "deepseek", Version: "v4-flash", Label: "DeepSeek V4 Flash", ReleaseDate: "2026-04-24", Reasoning: true, ContextWindow: 1000000, Preferred: true},
	{ID: "deepseek-reasoner", Provider: modelProviderDeepSeek, Family: "deepseek", Version: "reasoner", Label: "DeepSeek Reasoner", ReleaseDate: "2025-12-01", Reasoning: true, ContextWindow: 1000000, Preferred: true},
	{ID: "deepseek-chat", Provider: modelProviderDeepSeek, Family: "deepseek", Version: "chat", Label: "DeepSeek Chat", ReleaseDate: "2025-12-01", ContextWindow: 1000000, Preferred: true},
}
