// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package adapters

import "encoding/json"

// Native Claude Code CLI arguments used by Captain's Anthropic CLI runtime.
type AnthropicCLIOptions struct {
	// Directories outside the working directory that Claude Code may access.
	AddDir []string `json:"addDir,omitempty,omitzero"`

	// Named agent selected for the current session.
	Agent *string `json:"agent,omitempty,omitzero"`

	// Inline JSON object defining custom agents.
	Agents *json.RawMessage `json:"agents,omitempty,omitzero"`

	// Whether permission bypass may be selected without being the default mode.
	AllowDangerouslySkipPermissions *bool `json:"allowDangerouslySkipPermissions,omitempty,omitzero"`

	// Claude Code tools allowed by Captain's tool policy.
	AllowedTools []string `json:"allowedTools,omitempty,omitzero"`

	// Additional instructions appended to Claude Code's system prompt.
	AppendSystemPrompt *string `json:"appendSystemPrompt,omitempty,omitzero"`

	// Whether Claude compacts conversation context automatically.
	Autocompact *bool `json:"autocompact,omitempty,omitzero"`

	// Whether terminal output is optimized for screen readers.
	AxScreenReader *bool `json:"axScreenReader,omitempty,omitzero"`

	// Whether the Claude Code session runs in the background.
	Background *bool `json:"background,omitempty,omitzero"`

	// Whether Claude starts without hooks, skills, plugins, or settings.
	Bare *bool `json:"bare,omitempty,omitzero"`

	// Anthropic beta feature identifiers included in API requests.
	Betas []string `json:"betas,omitempty,omitzero"`

	// Whether Claude emits a shorter initial response.
	Brief *bool `json:"brief,omitempty,omitzero"`

	// Whether Claude Code connects to the Chrome browser integration.
	Chrome *bool `json:"chrome,omitempty,omitzero"`

	// Whether the prompt is executed as a Claude Code cloud session.
	Cloud *bool `json:"cloud,omitempty,omitzero"`

	// Whether Claude continues the most recent session in the working directory.
	Continue *bool `json:"continue,omitempty,omitzero"`

	// Whether all permission checks are bypassed.
	DangerouslySkipPermissions *bool `json:"dangerouslySkipPermissions,omitempty,omitzero"`

	// Debug category selector or switch for Claude Code diagnostics.
	Debug *json.RawMessage `json:"debug,omitempty,omitzero"`

	// Path receiving Claude Code diagnostic logs.
	DebugFile *string `json:"debugFile,omitempty,omitzero"`

	// Whether skills and slash commands are disabled.
	DisableSlashCommands *bool `json:"disableSlashCommands,omitempty,omitzero"`

	// Claude Code tools denied by Captain's tool policy.
	DisallowedTools []string `json:"disallowedTools,omitempty,omitzero"`

	// Reasoning effort requested from supported Claude models.
	Effort *AnthropicCLIOptionsEffort `json:"effort,omitempty,omitzero"`

	// Remote cloud environment selected for the session.
	Environment *string `json:"environment,omitempty,omitzero"`

	// Dynamic Claude Code system-prompt sections omitted from the request.
	ExcludeDynamicSystemPromptSections []string `json:"excludeDynamicSystemPromptSections,omitempty,omitzero"`

	// Model used if the requested model is overloaded.
	FallbackModel *string `json:"fallbackModel,omitempty,omitzero"`

	// File resources downloaded and supplied to the conversation at startup.
	File []string `json:"file,omitempty,omitzero"`

	// Whether resuming creates a new session identifier.
	ForkSession *bool `json:"forkSession,omitempty,omitzero"`

	// Whether subagent text is forwarded into the parent output stream.
	ForwardSubagentText *bool `json:"forwardSubagentText,omitempty,omitzero"`

	// Pull request number whose linked Claude session is resumed.
	FromPr *int `json:"fromPr,omitempty,omitzero"`

	// Whether Claude Code prints command help and exits.
	Help *bool `json:"help,omitempty,omitzero"`

	// Whether Claude Code connects automatically to an available IDE.
	Ide *bool `json:"ide,omitempty,omitzero"`

	// Whether hook lifecycle events appear in stream-json output.
	IncludeHookEvents *bool `json:"includeHookEvents,omitempty,omitzero"`

	// Whether partial assistant chunks appear in stream-json output.
	IncludePartialMessages *bool `json:"includePartialMessages,omitempty,omitzero"`

	// Format used to parse standard input.
	InputFormat *AnthropicCLIOptionsInputFormat `json:"inputFormat,omitempty,omitzero"`

	// JSON Schema constraining Claude's final response.
	JsonSchema *json.RawMessage `json:"jsonSchema,omitempty,omitzero"`

	// Maximum spend in US dollars for the CLI request.
	MaxBudgetUsd *float64 `json:"maxBudgetUsd,omitempty,omitzero"`

	// MCP server configuration files or inline JSON passed to Claude Code.
	McpConfig []string `json:"mcpConfig,omitempty,omitzero"`

	// Model alias or full model identifier passed to Claude Code.
	Model *string `json:"model,omitempty,omitzero"`

	// Display name assigned to the Claude Code session.
	Name *string `json:"name,omitempty,omitzero"`

	// Whether Claude Code explicitly avoids the Chrome browser integration.
	NoChrome *bool `json:"noChrome,omitempty,omitzero"`

	// Whether Claude Code avoids saving the session to disk.
	NoSessionPersistence *bool `json:"noSessionPersistence,omitempty,omitzero"`

	// Format used for Claude Code output.
	OutputFormat *string `json:"outputFormat,omitempty,omitzero"`

	// Claude Code permission posture translated from Captain policy.
	PermissionMode *AnthropicCLIOptionsPermissionMode `json:"permissionMode,omitempty,omitzero"`

	// Transport used for permission prompts in non-interactive mode.
	PermissionPrompts *AnthropicCLIOptionsPermissionPrompts `json:"permissionPrompts,omitempty,omitzero"`

	// Claude Code plugin directories loaded for this session.
	PluginDir []string `json:"pluginDir,omitempty,omitzero"`

	// Remote plugin URLs downloaded and loaded for the session.
	PluginUrl []string `json:"pluginUrl,omitempty,omitzero"`

	// Whether Claude prints one response and exits instead of opening an interactive
	// session.
	Print *bool `json:"print,omitempty,omitzero"`

	// Prompt text written to Claude Code standard input.
	Prompt *string `json:"prompt,omitempty,omitzero"`

	// Whether Claude emits suggested follow-up prompts.
	PromptSuggestions *bool `json:"promptSuggestions,omitempty,omitzero"`

	// Whether the local session can be controlled from claude.ai.
	RemoteControl *bool `json:"remoteControl,omitempty,omitzero"`

	// Prefix used for remote-control session names.
	RemoteControlSessionNamePrefix *string `json:"remoteControlSessionNamePrefix,omitempty,omitzero"`

	// Whether stdin user messages are echoed back into stream-json output.
	ReplayUserMessages *bool `json:"replayUserMessages,omitempty,omitzero"`

	// Whether networking and filesystem access are restricted.
	Restricted *bool `json:"restricted,omitempty,omitzero"`

	// Session identifier resumed by Claude Code.
	Resume *string `json:"resume,omitempty,omitzero"`

	// Whether built-in skills, hooks, filesystem MCP servers, and command files are
	// disabled.
	SafeMode *bool `json:"safeMode,omitempty,omitzero"`

	// Explicit UUID assigned to a new Claude Code session.
	SessionId *string `json:"sessionId,omitempty,omitzero"`

	// Filesystem setting scopes loaded by Claude Code.
	SettingSources []AnthropicCLIOptionsSettingSourcesElem `json:"settingSources,omitempty,omitzero"`

	// Settings file or inline JSON generated for sandbox and monitoring behavior.
	Settings *string `json:"settings,omitempty,omitzero"`

	// Whether Claude uses only MCP servers supplied by --mcp-config.
	StrictMcpConfig *bool `json:"strictMcpConfig,omitempty,omitzero"`

	// System prompt replacing Claude Code's default instructions.
	SystemPrompt *string `json:"systemPrompt,omitempty,omitzero"`

	// Snapshot file supplying system-prompt content.
	SystemPromptSnapshot *string `json:"systemPromptSnapshot,omitempty,omitzero"`

	// Whether a remote Claude session is teleported into the local terminal.
	Teleport *bool `json:"teleport,omitempty,omitzero"`

	// Whether Claude creates a tmux worktree session.
	Tmux *bool `json:"tmux,omitempty,omitzero"`

	// Built-in Claude Code tool names made available to the session.
	Tools []string `json:"tools,omitempty,omitzero"`

	// Whether Claude emits complete stream-json diagnostic events.
	Verbose *bool `json:"verbose,omitempty,omitzero"`

	// Whether Claude Code prints its version and exits.
	Version *bool `json:"version,omitempty,omitzero"`

	// Whether Claude starts in an isolated Git worktree, optionally using a supplied
	// name.
	Worktree *json.RawMessage `json:"worktree,omitempty,omitzero"`
}

type AnthropicCLIOptionsEffort string

const AnthropicCLIOptionsEffortHigh AnthropicCLIOptionsEffort = "high"
const AnthropicCLIOptionsEffortLow AnthropicCLIOptionsEffort = "low"
const AnthropicCLIOptionsEffortMax AnthropicCLIOptionsEffort = "max"
const AnthropicCLIOptionsEffortMedium AnthropicCLIOptionsEffort = "medium"
const AnthropicCLIOptionsEffortXhigh AnthropicCLIOptionsEffort = "xhigh"

type AnthropicCLIOptionsInputFormat string

const AnthropicCLIOptionsInputFormatStreamJson AnthropicCLIOptionsInputFormat = "stream-json"
const AnthropicCLIOptionsInputFormatText AnthropicCLIOptionsInputFormat = "text"

type AnthropicCLIOptionsPermissionMode string

const AnthropicCLIOptionsPermissionModeAcceptEdits AnthropicCLIOptionsPermissionMode = "acceptEdits"
const AnthropicCLIOptionsPermissionModeAuto AnthropicCLIOptionsPermissionMode = "auto"
const AnthropicCLIOptionsPermissionModeBypassPermissions AnthropicCLIOptionsPermissionMode = "bypassPermissions"
const AnthropicCLIOptionsPermissionModeDontAsk AnthropicCLIOptionsPermissionMode = "dontAsk"
const AnthropicCLIOptionsPermissionModeManual AnthropicCLIOptionsPermissionMode = "manual"
const AnthropicCLIOptionsPermissionModePlan AnthropicCLIOptionsPermissionMode = "plan"

type AnthropicCLIOptionsPermissionPrompts string

const AnthropicCLIOptionsPermissionPromptsHost AnthropicCLIOptionsPermissionPrompts = "host"
const AnthropicCLIOptionsPermissionPromptsNone AnthropicCLIOptionsPermissionPrompts = "none"

type AnthropicCLIOptionsSettingSourcesElem string

const AnthropicCLIOptionsSettingSourcesElemLocal AnthropicCLIOptionsSettingSourcesElem = "local"
const AnthropicCLIOptionsSettingSourcesElemProject AnthropicCLIOptionsSettingSourcesElem = "project"
const AnthropicCLIOptionsSettingSourcesElemUser AnthropicCLIOptionsSettingSourcesElem = "user"
