// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package adapters

import "encoding/json"

// Native Claude Agent SDK options and Captain bridge arguments used by the
// Anthropic agent runtime.
type AnthropicAgentOptions struct {
	// JavaScript AbortController used to cancel an SDK query.
	AbortController *json.RawMessage `json:"abortController,omitempty,omitzero"`

	// Directories outside cwd that Claude's tools may access.
	AdditionalDirectories []string `json:"additionalDirectories,omitempty,omitzero"`

	// Named SDK agent selected as the main execution agent.
	Agent *string `json:"agent,omitempty,omitzero"`

	// Whether progress summaries are generated for long-running agent work.
	AgentProgressSummaries *bool `json:"agentProgressSummaries,omitempty,omitzero"`

	// Named subagent definitions made available to Claude.
	Agents *json.RawMessage `json:"agents,omitempty,omitzero"`

	// Required Agent SDK acknowledgement before bypassPermissions may be used.
	AllowDangerouslySkipPermissions *bool `json:"allowDangerouslySkipPermissions,omitempty,omitzero"`

	// Tool names the Agent SDK may use without being denied by Captain's policy.
	AllowedTools []string `json:"allowedTools,omitempty,omitzero"`

	// Captain bridge text appended to the Agent SDK system prompt.
	AppendSystemPrompt *string `json:"appendSystemPrompt,omitempty,omitzero"`

	// Whether the bridge asks Captain to broker each caller-tool decision.
	ApprovalMode *AnthropicAgentOptionsApprovalMode `json:"approvalMode,omitempty,omitzero"`

	// Anthropic beta feature identifiers enabled for the SDK query.
	Betas []string `json:"betas,omitempty,omitzero"`

	// Reserved metadata key correlating MCP tool calls with SDK hook events.
	CallerToolUseIDKey *string `json:"callerToolUseIDKey,omitempty,omitzero"`

	// Agent SDK callback used to ask Captain for a tool-use decision.
	CanUseTool *json.RawMessage `json:"canUseTool,omitempty,omitzero"`

	// Whether the SDK continues the most recent conversation in cwd.
	Continue *bool `json:"continue,omitempty,omitzero"`

	// Working directory used by Claude Code tools and settings discovery.
	Cwd *string `json:"cwd,omitempty,omitzero"`

	// Whether Agent SDK debug logging is enabled.
	Debug *bool `json:"debug,omitempty,omitzero"`

	// Path receiving Agent SDK debug logs.
	DebugFile *string `json:"debugFile,omitempty,omitzero"`

	// Tool names explicitly denied by Captain's policy.
	DisallowedTools []string `json:"disallowedTools,omitempty,omitzero"`

	// Adaptive reasoning effort used by supported Claude models.
	Effort *AnthropicAgentOptionsEffort `json:"effort,omitempty,omitzero"`

	// Whether the SDK records file state so edits can be rewound.
	EnableFileCheckpointing *bool `json:"enableFileCheckpointing,omitempty,omitzero"`

	// Environment variables supplied to the Claude Code child process.
	Env Environment `json:"env,omitempty,omitzero"`

	// JavaScript runtime used to launch the Agent SDK child process.
	Executable *string `json:"executable,omitempty,omitzero"`

	// Arguments prepended when launching the Agent SDK runtime.
	ExecutableArgs []string `json:"executableArgs,omitempty,omitzero"`

	// Additional raw command-line arguments passed by the SDK to Claude Code.
	ExtraArgs *json.RawMessage `json:"extraArgs,omitempty,omitzero"`

	// Model used if the requested Claude model is unavailable.
	FallbackModel *string `json:"fallbackModel,omitempty,omitzero"`

	// Whether resuming creates a new session identifier instead of continuing in
	// place.
	ForkSession *bool `json:"forkSession,omitempty,omitzero"`

	// Whether subagent text is forwarded into the parent query stream.
	ForwardSubagentText *bool `json:"forwardSubagentText,omitempty,omitzero"`

	// Claude lifecycle and tool hooks installed for monitoring and caller-tool
	// correlation.
	Hooks *json.RawMessage `json:"hooks,omitempty,omitzero"`

	// Whether hook lifecycle events are emitted in the SDK message stream.
	IncludeHookEvents *bool `json:"includeHookEvents,omitempty,omitzero"`

	// Whether partial assistant message chunks are emitted by the SDK.
	IncludePartialMessages *bool `json:"includePartialMessages,omitempty,omitzero"`

	// Maximum milliseconds allowed when loading a persisted session.
	LoadTimeoutMs *int `json:"loadTimeoutMs,omitempty,omitzero"`

	// Enterprise-managed Claude Code settings applied to the query.
	ManagedSettings *json.RawMessage `json:"managedSettings,omitempty,omitzero"`

	// Maximum spend in US dollars before the SDK stops.
	MaxBudgetUsd *float64 `json:"maxBudgetUsd,omitempty,omitzero"`

	// Maximum tokens allocated to extended thinking.
	MaxThinkingTokens *int `json:"maxThinkingTokens,omitempty,omitzero"`

	// Maximum number of agent turns before the SDK stops.
	MaxTurns *int `json:"maxTurns,omitempty,omitzero"`

	// Agent SDK MCP server definitions injected for Captain caller tools.
	McpServers *json.RawMessage `json:"mcpServers,omitempty,omitzero"`

	// Claude model identifier passed to the Agent SDK.
	Model *string `json:"model,omitempty,omitzero"`

	// Captain bridge URL receiving SDK lifecycle hook events.
	MonitorUrl *string `json:"monitorUrl,omitempty,omitzero"`

	// Callback handling MCP elicitation requests from the SDK.
	OnElicitation *json.RawMessage `json:"onElicitation,omitempty,omitzero"`

	// Callback handling native Claude user-dialog requests.
	OnUserDialog *json.RawMessage `json:"onUserDialog,omitempty,omitzero"`

	// Structured-output JSON Schema passed to the Agent SDK.
	OutputFormat *json.RawMessage `json:"outputFormat,omitempty,omitzero"`

	// Captain bridge JSON Schema converted into the SDK outputFormat option.
	OutputSchema *json.RawMessage `json:"outputSchema,omitempty,omitzero"`

	// Filesystem path to the Claude Code executable launched by the SDK.
	PathToClaudeCodeExecutable *string `json:"pathToClaudeCodeExecutable,omitempty,omitzero"`

	// Declares that the host can stop individual background tasks, so an interrupt
	// only aborts the current turn.
	PerTaskStopAffordance *bool `json:"perTaskStopAffordance,omitempty,omitzero"`

	// Claude Code permission posture translated from Captain's runtime policy.
	PermissionMode *AnthropicAgentOptionsPermissionMode `json:"permissionMode,omitempty,omitzero"`

	// MCP tool name used by Claude Code to request permission decisions.
	PermissionPromptToolName *string `json:"permissionPromptToolName,omitempty,omitzero"`

	// Who answers permission prompts: the host through canUseTool, or nobody so
	// prompting requests are denied.
	PermissionPrompts *AnthropicAgentOptionsPermissionPrompts `json:"permissionPrompts,omitempty,omitzero"`

	// Whether the Agent SDK persists the session to disk.
	PersistSession *bool `json:"persistSession,omitempty,omitzero"`

	// Additional instructions injected when Claude enters plan mode.
	PlanModeInstructions *string `json:"planModeInstructions,omitempty,omitzero"`

	// How plugins reach the Claude Code process: --plugin-dir arguments or the
	// initialize request.
	PluginDelivery *AnthropicAgentOptionsPluginDelivery `json:"pluginDelivery,omitempty,omitzero"`

	// Local Claude Code plugin directories loaded for the query.
	Plugins *json.RawMessage `json:"plugins,omitempty,omitzero"`

	// Trusted checkout that cwd is a worktree of; project settings, .mcp.json and
	// .claude config trees load from here instead of cwd.
	ProjectConfigRoot *string `json:"projectConfigRoot,omitempty,omitzero"`

	// File and image attachments sent in a Captain bridge prompt request.
	PromptAttachments *json.RawMessage `json:"promptAttachments,omitempty,omitzero"`

	// Whether the SDK emits suggested follow-up prompts.
	PromptSuggestions *bool `json:"promptSuggestions,omitempty,omitzero"`

	// Text sent in a Captain bridge prompt request.
	PromptText *string `json:"promptText,omitempty,omitzero"`

	// Claude session identifier resumed by the Agent SDK.
	Resume *string `json:"resume,omitempty,omitzero"`

	// Guarded fork point paired with resumeSessionAt that discards the turn after the
	// kept chain entry.
	ResumeDropsTurn *string `json:"resumeDropsTurn,omitempty,omitzero"`

	// Message identifier at which an existing session is resumed.
	ResumeSessionAt *string `json:"resumeSessionAt,omitempty,omitzero"`

	// Claude Agent SDK filesystem and command sandbox configuration.
	Sandbox *json.RawMessage `json:"sandbox,omitempty,omitzero"`

	// Explicit UUID assigned when starting a new Agent SDK session.
	SessionId *string `json:"sessionId,omitempty,omitzero"`

	// Custom storage implementation used for Agent SDK session data.
	SessionStore *json.RawMessage `json:"sessionStore,omitempty,omitzero"`

	// Callback invoked to flush custom session storage.
	SessionStoreFlush *json.RawMessage `json:"sessionStoreFlush,omitempty,omitzero"`

	// Filesystem setting scopes loaded by Claude Code.
	SettingSources []AnthropicAgentOptionsSettingSourcesElem `json:"settingSources,omitempty,omitzero"`

	// In-memory Claude Code settings applied to the query.
	Settings *json.RawMessage `json:"settings,omitempty,omitzero"`

	// Skill configuration made available to the Agent SDK query.
	Skills *json.RawMessage `json:"skills,omitempty,omitzero"`

	// Custom callback used by the SDK to start the Claude Code process.
	SpawnClaudeCodeProcess *json.RawMessage `json:"spawnClaudeCodeProcess,omitempty,omitzero"`

	// Agent SDK callback forwarding child-process diagnostics to Captain.
	Stderr *json.RawMessage `json:"stderr,omitempty,omitzero"`

	// Whether Claude ignores all MCP servers except those supplied in options.
	StrictMcpConfig *bool `json:"strictMcpConfig,omitempty,omitzero"`

	// User-dialog kinds the host declares it can render.
	SupportedDialogKinds []string `json:"supportedDialogKinds,omitempty,omitzero"`

	// System prompt string, string blocks, or custom/preset configuration used for
	// the session.
	SystemPrompt *json.RawMessage `json:"systemPrompt,omitempty,omitzero"`

	// Native budget constraints applied to SDK task execution.
	TaskBudget *json.RawMessage `json:"taskBudget,omitempty,omitzero"`

	// Detailed native thinking configuration beyond the effort level.
	Thinking *json.RawMessage `json:"thinking,omitempty,omitzero"`

	// Display title assigned to the Claude Agent SDK session.
	Title *string `json:"title,omitempty,omitzero"`

	// Alternate display names and descriptions for SDK tools.
	ToolAliases *json.RawMessage `json:"toolAliases,omitempty,omitzero"`

	// Native per-tool configuration supplied to the Agent SDK.
	ToolConfig *json.RawMessage `json:"toolConfig,omitempty,omitzero"`

	// Built-in tool preset or explicit SDK tool-name list.
	Tools *json.RawMessage `json:"tools,omitempty,omitzero"`

	// Deliver prompt text as written, without @path expansion, slash-command dispatch
	// or turn-start attachments.
	VerbatimPrompts *bool `json:"verbatimPrompts,omitempty,omitzero"`
}

type AnthropicAgentOptionsApprovalMode string

const AnthropicAgentOptionsApprovalModeAsk AnthropicAgentOptionsApprovalMode = "ask"
const AnthropicAgentOptionsApprovalModeAuto AnthropicAgentOptionsApprovalMode = "auto"

type AnthropicAgentOptionsEffort string

const AnthropicAgentOptionsEffortHigh AnthropicAgentOptionsEffort = "high"
const AnthropicAgentOptionsEffortLow AnthropicAgentOptionsEffort = "low"
const AnthropicAgentOptionsEffortMax AnthropicAgentOptionsEffort = "max"
const AnthropicAgentOptionsEffortMedium AnthropicAgentOptionsEffort = "medium"
const AnthropicAgentOptionsEffortXhigh AnthropicAgentOptionsEffort = "xhigh"

type AnthropicAgentOptionsPermissionMode string

const AnthropicAgentOptionsPermissionModeAcceptEdits AnthropicAgentOptionsPermissionMode = "acceptEdits"
const AnthropicAgentOptionsPermissionModeBypassPermissions AnthropicAgentOptionsPermissionMode = "bypassPermissions"
const AnthropicAgentOptionsPermissionModeDefault AnthropicAgentOptionsPermissionMode = "default"
const AnthropicAgentOptionsPermissionModeDontAsk AnthropicAgentOptionsPermissionMode = "dontAsk"
const AnthropicAgentOptionsPermissionModePlan AnthropicAgentOptionsPermissionMode = "plan"

type AnthropicAgentOptionsPermissionPrompts string

const AnthropicAgentOptionsPermissionPromptsHost AnthropicAgentOptionsPermissionPrompts = "host"
const AnthropicAgentOptionsPermissionPromptsNone AnthropicAgentOptionsPermissionPrompts = "none"

type AnthropicAgentOptionsPluginDelivery string

const AnthropicAgentOptionsPluginDeliveryArgv AnthropicAgentOptionsPluginDelivery = "argv"
const AnthropicAgentOptionsPluginDeliveryInitialize AnthropicAgentOptionsPluginDelivery = "initialize"

type AnthropicAgentOptionsSettingSourcesElem string

const AnthropicAgentOptionsSettingSourcesElemLocal AnthropicAgentOptionsSettingSourcesElem = "local"
const AnthropicAgentOptionsSettingSourcesElemProject AnthropicAgentOptionsSettingSourcesElem = "project"
const AnthropicAgentOptionsSettingSourcesElemUser AnthropicAgentOptionsSettingSourcesElem = "user"

// Environment variables supplied to the Claude Code child process.
type Environment map[string]string
