// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package adapters

import "encoding/json"

// Native Anthropic Messages API request options used by Captain's API runtime.
type AnthropicAPIOptions struct {
	// Top-level prompt-cache marker applied to the final cacheable block.
	CacheControl *json.RawMessage `json:"cache_control,omitempty,omitzero"`

	// Container identifier reused across Messages API requests.
	Container *string `json:"container,omitempty,omitzero"`

	// Geographic region requested for inference processing.
	InferenceGeo *string `json:"inference_geo,omitempty,omitzero"`

	// Maximum tokens generated before stopping, including extended-thinking tokens.
	MaxTokens int `json:"max_tokens"`

	// Alternating user and assistant messages sent to the Messages API.
	Messages json.RawMessage `json:"messages"`

	// Request metadata, including the optional user identifier.
	Metadata *json.RawMessage `json:"metadata,omitempty,omitzero"`

	// Anthropic model identifier used to complete the request.
	Model string `json:"model"`

	// Structured-output format and adaptive-thinking effort configuration.
	OutputConfig *json.RawMessage `json:"output_config,omitempty,omitzero"`

	// Capacity tier used to serve the request.
	ServiceTier *AnthropicAPIOptionsServiceTier `json:"service_tier,omitempty,omitzero"`

	// Text sequences that stop generation when encountered.
	StopSequences []string `json:"stop_sequences,omitempty,omitzero"`

	// Whether the Messages API returns server-sent streaming events.
	Stream *bool `json:"stream,omitempty,omitzero"`

	// System instruction blocks supplied outside the message list.
	System *json.RawMessage `json:"system,omitempty,omitzero"`

	// Sampling temperature between zero and one.
	Temperature *float64 `json:"temperature,omitempty,omitzero"`

	// Extended-thinking configuration for reasoning-capable models.
	Thinking *json.RawMessage `json:"thinking,omitempty,omitzero"`

	// Policy controlling whether and which native tool Claude should call.
	ToolChoice *json.RawMessage `json:"tool_choice,omitempty,omitzero"`

	// Native Anthropic tool definitions derived from Captain caller tools.
	Tools *json.RawMessage `json:"tools,omitempty,omitzero"`

	// Number of highest-probability tokens retained during sampling.
	TopK *int `json:"top_k,omitempty,omitzero"`

	// Cumulative probability mass retained during nucleus sampling.
	TopP *float64 `json:"top_p,omitempty,omitzero"`
}

type AnthropicAPIOptionsServiceTier string

const AnthropicAPIOptionsServiceTierAuto AnthropicAPIOptionsServiceTier = "auto"
const AnthropicAPIOptionsServiceTierStandardOnly AnthropicAPIOptionsServiceTier = "standard_only"
