// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package adapters

import "encoding/json"

// Native Gemini CLI arguments used by Captain's Google CLI runtime.
type GoogleCLIOptions struct {
	// Explicit acknowledgement required before raw output is enabled.
	AcceptRawOutputRisk *bool `json:"acceptRawOutputRisk,omitempty,omitzero"`

	// Whether Gemini runs as an Agent Client Protocol server.
	Acp *bool `json:"acp,omitempty,omitzero"`

	// Additional administrator policy files applied by Gemini CLI.
	AdminPolicy []string `json:"adminPolicy,omitempty,omitzero"`

	// MCP server names allowed to connect in ACP mode.
	AllowedMcpServerNames []string `json:"allowedMcpServerNames,omitempty,omitzero"`

	// Deprecated list of tools allowed to execute without confirmation.
	AllowedTools []string `json:"allowedTools,omitempty,omitzero"`

	// Gemini tool-approval posture translated from Captain policy.
	ApprovalMode *GoogleCLIOptionsApprovalMode `json:"approvalMode,omitempty,omitzero"`

	// Whether Gemini CLI debug logging is enabled.
	Debug *bool `json:"debug,omitempty,omitzero"`

	// Stored Gemini session index deleted before exit.
	DeleteSession *int `json:"deleteSession,omitempty,omitzero"`

	// Whether Gemini enables experimental Agent Client Protocol behavior.
	ExperimentalAcp *bool `json:"experimentalAcp,omitempty,omitzero"`

	// Gemini CLI extensions enabled for the session.
	Extensions []string `json:"extensions,omitempty,omitzero"`

	// Whether Gemini prints command help and exits.
	Help *bool `json:"help,omitempty,omitzero"`

	// Additional workspace directories included in the Gemini session.
	IncludeDirectories []string `json:"includeDirectories,omitempty,omitzero"`

	// Whether Gemini lists installed extensions and exits.
	ListExtensions *bool `json:"listExtensions,omitempty,omitzero"`

	// Whether Gemini lists stored sessions for the current project.
	ListSessions *bool `json:"listSessions,omitempty,omitzero"`

	// Gemini model identifier used for the request.
	Model *string `json:"model,omitempty,omitzero"`

	// Format used for Gemini CLI output.
	OutputFormat *string `json:"outputFormat,omitempty,omitzero"`

	// Policy files applied by Gemini CLI.
	Policy []string `json:"policy,omitempty,omitzero"`

	// Composed prompt text written to Gemini standard input.
	Prompt *string `json:"prompt,omitempty,omitzero"`

	// Prompt text supplied directly by the --prompt flag.
	PromptFlag *string `json:"promptFlag,omitempty,omitzero"`

	// Initial prompt followed by an interactive Gemini session.
	PromptInteractive *string `json:"promptInteractive,omitempty,omitzero"`

	// Whether terminal control sequences are preserved in streamed output.
	RawOutput *bool `json:"rawOutput,omitempty,omitzero"`

	// Session index or latest selector resumed by Gemini CLI.
	Resume *json.RawMessage `json:"resume,omitempty,omitzero"`

	// Whether Gemini enables its native sandbox, optionally with a sandbox image.
	Sandbox *json.RawMessage `json:"sandbox,omitempty,omitzero"`

	// Whether interactive output is optimized for screen readers.
	ScreenReader *bool `json:"screenReader,omitempty,omitzero"`

	// Path to a Gemini session file loaded for execution.
	SessionFile *string `json:"sessionFile,omitempty,omitzero"`

	// Explicit Gemini session identifier selected for execution.
	SessionId *string `json:"sessionId,omitempty,omitzero"`

	// Whether Gemini skips workspace trust validation.
	SkipTrust *bool `json:"skipTrust,omitempty,omitzero"`

	// Whether Gemini prints its version and exits.
	Version *bool `json:"version,omitempty,omitzero"`

	// Whether Gemini creates and runs in a Git worktree.
	Worktree *json.RawMessage `json:"worktree,omitempty,omitzero"`

	// Whether Gemini automatically approves every tool action.
	Yolo *bool `json:"yolo,omitempty,omitzero"`
}

type GoogleCLIOptionsApprovalMode string

const GoogleCLIOptionsApprovalModeAutoEdit GoogleCLIOptionsApprovalMode = "auto_edit"
const GoogleCLIOptionsApprovalModeDefault GoogleCLIOptionsApprovalMode = "default"
const GoogleCLIOptionsApprovalModePlan GoogleCLIOptionsApprovalMode = "plan"
const GoogleCLIOptionsApprovalModeYolo GoogleCLIOptionsApprovalMode = "yolo"
