// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package adapters

import "encoding/json"

// Native Google Gen AI GenerateContent arguments and configuration used by
// Captain's API runtime.
type GoogleAPIOptions struct {
	// Whether timestamps are requested for audio input or output.
	AudioTimestamp *bool `json:"audioTimestamp,omitempty,omitzero"`

	// Resource name of previously cached content included in the request.
	CachedContent *string `json:"cachedContent,omitempty,omitzero"`

	// Number of candidate responses requested from the model.
	CandidateCount *int `json:"candidateCount,omitempty,omitzero"`

	// Conversation parts, user input, attachments, and tool results sent to the
	// model.
	Contents json.RawMessage `json:"contents"`

	// Whether enhanced civic-information answers are enabled.
	EnableEnhancedCivicAnswers *bool `json:"enableEnhancedCivicAnswers,omitempty,omitzero"`

	// Penalty scaled by how often a token has appeared in generated text.
	FrequencyPenalty *float64 `json:"frequencyPenalty,omitempty,omitzero"`

	// Per-request HTTP transport and API version settings.
	HttpOptions *json.RawMessage `json:"httpOptions,omitempty,omitzero"`

	// Generation options for image response modalities.
	ImageConfig *json.RawMessage `json:"imageConfig,omitempty,omitzero"`

	// String key-value labels attached to the request for billing and reporting.
	Labels Labels `json:"labels,omitempty,omitzero"`

	// Number of top token log probabilities returned per decoding step.
	Logprobs *int `json:"logprobs,omitempty,omitzero"`

	// Maximum number of tokens generated in the response.
	MaxOutputTokens *int `json:"maxOutputTokens,omitempty,omitzero"`

	// Resolution requested when the model processes media inputs.
	MediaResolution *string `json:"mediaResolution,omitempty,omitzero"`

	// Google model identifier passed to GenerateContent.
	Model string `json:"model"`

	// Model Armor template and filtering behavior applied to the request.
	ModelArmorConfig *json.RawMessage `json:"modelArmorConfig,omitempty,omitzero"`

	// Constraints used by automatic model selection.
	ModelSelectionConfig *json.RawMessage `json:"modelSelectionConfig,omitempty,omitzero"`

	// Penalty applied when a token has appeared in the generated text.
	PresencePenalty *float64 `json:"presencePenalty,omitempty,omitzero"`

	// Raw JSON Schema constraining generated JSON output.
	ResponseJsonSchema *json.RawMessage `json:"responseJsonSchema,omitempty,omitzero"`

	// Whether token log probabilities are included in the response.
	ResponseLogprobs *bool `json:"responseLogprobs,omitempty,omitzero"`

	// MIME type requested for structured or plain-text output.
	ResponseMimeType *string `json:"responseMimeType,omitempty,omitzero"`

	// Requested output modalities such as text, image, or audio.
	ResponseModalities []string `json:"responseModalities,omitempty,omitzero"`

	// Google schema constraining a structured response.
	ResponseSchema *json.RawMessage `json:"responseSchema,omitempty,omitzero"`

	// Model routing behavior for supported Google endpoints.
	RoutingConfig *json.RawMessage `json:"routingConfig,omitempty,omitzero"`

	// Per-category content safety thresholds applied to the request.
	SafetySettings *json.RawMessage `json:"safetySettings,omitempty,omitzero"`

	// Fixed sampling seed used for best-effort deterministic generation.
	Seed *int `json:"seed,omitempty,omitzero"`

	// Google processing tier used for the request.
	ServiceTier *string `json:"serviceTier,omitempty,omitzero"`

	// Voice and language settings used for generated speech.
	SpeechConfig *json.RawMessage `json:"speechConfig,omitempty,omitzero"`

	// Text sequences that stop generation when encountered.
	StopSequences []string `json:"stopSequences,omitempty,omitzero"`

	// Whether GenerateContent returns a stream of response chunks.
	Stream *bool `json:"stream,omitempty,omitzero"`

	// System instruction content supplied separately from the conversation.
	SystemInstruction *json.RawMessage `json:"systemInstruction,omitempty,omitzero"`

	// Sampling temperature used for response generation.
	Temperature *float64 `json:"temperature,omitempty,omitzero"`

	// Thinking budget and inclusion settings for reasoning-capable Gemini models.
	ThinkingConfig *json.RawMessage `json:"thinkingConfig,omitempty,omitzero"`

	// Native policy controlling Google function-calling behavior.
	ToolConfig *json.RawMessage `json:"toolConfig,omitempty,omitzero"`

	// Native Google tool declarations derived from Captain caller tools.
	Tools *json.RawMessage `json:"tools,omitempty,omitzero"`

	// Number of highest-probability tokens retained during sampling.
	TopK *float64 `json:"topK,omitempty,omitzero"`

	// Cumulative probability mass retained during nucleus sampling.
	TopP *float64 `json:"topP,omitempty,omitzero"`
}

// String key-value labels attached to the request for billing and reporting.
type Labels map[string]string
