// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package adapters

// Native Codex exec CLI arguments used by Captain's OpenAI CLI runtime.
type OpenAICLIOptions struct {
	// Additional directories granted write access alongside the primary workspace.
	AddDir []string `json:"addDir,omitempty,omitzero"`

	// Whether Codex chooses when to request command approval.
	ApproveForMe *bool `json:"approveForMe,omitempty,omitzero"`

	// Directory used as the Codex workspace root.
	Cd *string `json:"cd,omitempty,omitzero"`

	// Color policy used for human-readable Codex output.
	Color *OpenAICLIOptionsColor `json:"color,omitempty,omitzero"`

	// Codex non-interactive execution subcommand.
	Command *string `json:"command,omitempty,omitzero"`

	// Codex TOML key-value overrides emitted on the command line.
	Config []string `json:"config,omitempty,omitzero"`

	// Whether Codex executes without approval prompts or sandbox isolation.
	DangerouslyBypassApprovalsAndSandbox *bool `json:"dangerouslyBypassApprovalsAndSandbox,omitempty,omitzero"`

	// Whether Codex runs project hooks without trust confirmation.
	DangerouslyBypassHookTrust *bool `json:"dangerouslyBypassHookTrust,omitempty,omitzero"`

	// Codex feature flags disabled for this invocation.
	Disable []string `json:"disable,omitempty,omitzero"`

	// Codex feature flags enabled for this invocation.
	Enable []string `json:"enable,omitempty,omitzero"`

	// Whether Codex avoids persisting session files.
	Ephemeral *bool `json:"ephemeral,omitempty,omitzero"`

	// Whether Codex prints exec command help and exits.
	Help *bool `json:"help,omitempty,omitzero"`

	// Whether Codex skips repository instructions and hooks.
	IgnoreRules *bool `json:"ignoreRules,omitempty,omitzero"`

	// Whether Codex skips user-level configuration and instructions.
	IgnoreUserConfig *bool `json:"ignoreUserConfig,omitempty,omitzero"`

	// Local image paths attached to the initial prompt.
	Image []string `json:"image,omitempty,omitzero"`

	// Whether Codex prints newline-delimited JSON events.
	Json *bool `json:"json,omitempty,omitzero"`

	// Local model provider selected when --oss is active.
	LocalProvider *string `json:"localProvider,omitempty,omitzero"`

	// Codex model identifier used for the execution.
	Model *string `json:"model,omitempty,omitzero"`

	// Whether Codex uses a local open-source model provider.
	Oss *bool `json:"oss,omitempty,omitzero"`

	// File path receiving the final assistant message.
	OutputLastMessage *string `json:"outputLastMessage,omitempty,omitzero"`

	// Path to a JSON Schema constraining the final response.
	OutputSchema *string `json:"outputSchema,omitempty,omitzero"`

	// Named Codex configuration profile loaded for the invocation.
	Profile *string `json:"profile,omitempty,omitzero"`

	// Prompt text written to Codex standard input.
	Prompt *string `json:"prompt,omitempty,omitzero"`

	// Codex thread identifier passed to the exec resume subcommand.
	Resume *string `json:"resume,omitempty,omitzero"`

	// Whether exec resume ignores cwd filtering while selecting a thread.
	ResumeAll *bool `json:"resumeAll,omitempty,omitzero"`

	// Whether exec resume selects the most recent Codex thread.
	ResumeLast *bool `json:"resumeLast,omitempty,omitzero"`

	// Codex command-execution sandbox mode.
	Sandbox *OpenAICLIOptionsSandbox `json:"sandbox,omitempty,omitzero"`

	// Whether Codex runs when the working directory is outside a Git repository.
	SkipGitRepoCheck *bool `json:"skipGitRepoCheck,omitempty,omitzero"`

	// Whether unknown configuration keys cause an error.
	StrictConfig *bool `json:"strictConfig,omitempty,omitzero"`

	// Source label attached to the created Codex thread.
	ThreadSource *string `json:"threadSource,omitempty,omitzero"`

	// Whether Codex prints its version and exits.
	Version *bool `json:"version,omitempty,omitzero"`

	// Whether Codex creates and uses a temporary Git worktree.
	Worktree *bool `json:"worktree,omitempty,omitzero"`
}

type OpenAICLIOptionsColor string

const OpenAICLIOptionsColorAlways OpenAICLIOptionsColor = "always"
const OpenAICLIOptionsColorAuto OpenAICLIOptionsColor = "auto"
const OpenAICLIOptionsColorNever OpenAICLIOptionsColor = "never"

type OpenAICLIOptionsSandbox string

const OpenAICLIOptionsSandboxDangerFullAccess OpenAICLIOptionsSandbox = "danger-full-access"
const OpenAICLIOptionsSandboxReadOnly OpenAICLIOptionsSandbox = "read-only"
const OpenAICLIOptionsSandboxWorkspaceWrite OpenAICLIOptionsSandbox = "workspace-write"
