// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package adapters

import "encoding/json"

// Up to sixteen string key-value pairs attached to the response.
type Metadata map[string]string

// Native OpenAI Responses API request options used by Captain's API runtime.
type OpenAIAPIOptions struct {
	// Whether OpenAI runs the response asynchronously in the background.
	Background *bool `json:"background,omitempty,omitzero"`

	// Additional response fields requested from the Responses API.
	Include []string `json:"include,omitempty,omitzero"`

	// Text, image, file, conversation, and function-result items sent to the model.
	Input json.RawMessage `json:"input"`

	// System or developer instructions inserted into the model context.
	Instructions *string `json:"instructions,omitempty,omitzero"`

	// Upper bound covering visible output and reasoning tokens.
	MaxOutputTokens *int `json:"max_output_tokens,omitempty,omitzero"`

	// Maximum total built-in tool calls processed in the response.
	MaxToolCalls *int `json:"max_tool_calls,omitempty,omitzero"`

	// Up to sixteen string key-value pairs attached to the response.
	Metadata Metadata `json:"metadata,omitempty,omitzero"`

	// OpenAI model identifier used to generate the response.
	Model string `json:"model"`

	// Whether the model may issue tool calls in parallel.
	ParallelToolCalls *bool `json:"parallel_tool_calls,omitempty,omitzero"`

	// Remote response identifier used for OpenAI-managed conversation state.
	PreviousResponseId *string `json:"previous_response_id,omitempty,omitzero"`

	// Reusable OpenAI prompt template reference and variables.
	Prompt *json.RawMessage `json:"prompt,omitempty,omitzero"`

	// Stable key used by OpenAI to improve prompt-cache routing.
	PromptCacheKey *string `json:"prompt_cache_key,omitempty,omitzero"`

	// Reasoning effort and summary configuration for reasoning models.
	Reasoning *json.RawMessage `json:"reasoning,omitempty,omitzero"`

	// Stable hashed identifier used for abuse detection.
	SafetyIdentifier *string `json:"safety_identifier,omitempty,omitzero"`

	// Processing tier used to serve the response.
	ServiceTier *OpenAIAPIOptionsServiceTier `json:"service_tier,omitempty,omitzero"`

	// Whether OpenAI stores the generated response for later retrieval.
	Store *bool `json:"store,omitempty,omitzero"`

	// Whether the response is returned as server-sent streaming events.
	Stream *bool `json:"stream,omitempty,omitzero"`

	// Sampling temperature between zero and two.
	Temperature *float64 `json:"temperature,omitempty,omitzero"`

	// Plain-text or JSON Schema output configuration.
	Text *json.RawMessage `json:"text,omitempty,omitzero"`

	// Policy selecting whether and which tool the model should call.
	ToolChoice *json.RawMessage `json:"tool_choice,omitempty,omitzero"`

	// Native Responses API tool definitions derived from Captain caller tools.
	Tools *json.RawMessage `json:"tools,omitempty,omitzero"`

	// Number of likely tokens returned with log probabilities at each position.
	TopLogprobs *int `json:"top_logprobs,omitempty,omitzero"`

	// Cumulative probability mass retained during nucleus sampling.
	TopP *float64 `json:"top_p,omitempty,omitzero"`

	// Strategy applied when conversation input exceeds the model context window.
	Truncation *OpenAIAPIOptionsTruncation `json:"truncation,omitempty,omitzero"`

	// Deprecated end-user identifier replaced by safety_identifier and
	// prompt_cache_key.
	User *string `json:"user,omitempty,omitzero"`
}

type OpenAIAPIOptionsServiceTier string

const OpenAIAPIOptionsServiceTierAuto OpenAIAPIOptionsServiceTier = "auto"
const OpenAIAPIOptionsServiceTierDefault OpenAIAPIOptionsServiceTier = "default"
const OpenAIAPIOptionsServiceTierFlex OpenAIAPIOptionsServiceTier = "flex"
const OpenAIAPIOptionsServiceTierPriority OpenAIAPIOptionsServiceTier = "priority"
const OpenAIAPIOptionsServiceTierScale OpenAIAPIOptionsServiceTier = "scale"

type OpenAIAPIOptionsTruncation string

const OpenAIAPIOptionsTruncationAuto OpenAIAPIOptionsTruncation = "auto"
const OpenAIAPIOptionsTruncationDisabled OpenAIAPIOptionsTruncation = "disabled"
