// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package adapters

import "encoding/json"

// Parameters sent in the Codex app-server initialize request.
type Initialize struct {
	// Experimental protocol capabilities supported by the client.
	Capabilities *json.RawMessage `json:"capabilities,omitempty,omitzero"`

	// Name, title, and version identifying the app-server client.
	ClientInfo *json.RawMessage `json:"clientInfo,omitempty,omitzero"`
}

// Native Codex app-server initialize, thread, and turn arguments used by Captain's
// OpenAI agent runtime.
type OpenAIAgentOptions struct {
	// Parameters sent in the Codex app-server initialize request.
	Initialize *Initialize `json:"initialize,omitempty,omitzero"`

	// Parameters used to resume an existing Codex app-server thread.
	ThreadResume *ThreadResume `json:"threadResume,omitempty,omitzero"`

	// Parameters used to start a new Codex app-server thread.
	ThreadStart *ThreadStart `json:"threadStart,omitempty,omitzero"`

	// Parameters used to start a turn on an active Codex app-server thread.
	TurnStart *TurnStart `json:"turnStart,omitempty,omitzero"`
}

type OpenAIAgentOptionsThreadResumeApprovalsReviewer string

const OpenAIAgentOptionsThreadResumeApprovalsReviewerAutoReview OpenAIAgentOptionsThreadResumeApprovalsReviewer = "auto_review"
const OpenAIAgentOptionsThreadResumeApprovalsReviewerGuardianSubagent OpenAIAgentOptionsThreadResumeApprovalsReviewer = "guardian_subagent"
const OpenAIAgentOptionsThreadResumeApprovalsReviewerUser OpenAIAgentOptionsThreadResumeApprovalsReviewer = "user"

type OpenAIAgentOptionsThreadResumeSandbox string

const OpenAIAgentOptionsThreadResumeSandboxDangerFullAccess OpenAIAgentOptionsThreadResumeSandbox = "danger-full-access"
const OpenAIAgentOptionsThreadResumeSandboxReadOnly OpenAIAgentOptionsThreadResumeSandbox = "read-only"
const OpenAIAgentOptionsThreadResumeSandboxWorkspaceWrite OpenAIAgentOptionsThreadResumeSandbox = "workspace-write"

type OpenAIAgentOptionsThreadStartApprovalsReviewer string

const OpenAIAgentOptionsThreadStartApprovalsReviewerAutoReview OpenAIAgentOptionsThreadStartApprovalsReviewer = "auto_review"
const OpenAIAgentOptionsThreadStartApprovalsReviewerGuardianSubagent OpenAIAgentOptionsThreadStartApprovalsReviewer = "guardian_subagent"
const OpenAIAgentOptionsThreadStartApprovalsReviewerUser OpenAIAgentOptionsThreadStartApprovalsReviewer = "user"

type OpenAIAgentOptionsThreadStartSandbox string

const OpenAIAgentOptionsThreadStartSandboxDangerFullAccess OpenAIAgentOptionsThreadStartSandbox = "danger-full-access"
const OpenAIAgentOptionsThreadStartSandboxReadOnly OpenAIAgentOptionsThreadStartSandbox = "read-only"
const OpenAIAgentOptionsThreadStartSandboxWorkspaceWrite OpenAIAgentOptionsThreadStartSandbox = "workspace-write"

type OpenAIAgentOptionsTurnStartApprovalsReviewer string

const OpenAIAgentOptionsTurnStartApprovalsReviewerAutoReview OpenAIAgentOptionsTurnStartApprovalsReviewer = "auto_review"
const OpenAIAgentOptionsTurnStartApprovalsReviewerGuardianSubagent OpenAIAgentOptionsTurnStartApprovalsReviewer = "guardian_subagent"
const OpenAIAgentOptionsTurnStartApprovalsReviewerUser OpenAIAgentOptionsTurnStartApprovalsReviewer = "user"

// Parameters used to resume an existing Codex app-server thread.
type ThreadResume struct {
	// Approval policy override applied while resuming the thread.
	ApprovalPolicy *json.RawMessage `json:"approvalPolicy,omitempty,omitzero"`

	// Reviewer override applied to the resumed thread.
	ApprovalsReviewer *OpenAIAgentOptionsThreadResumeApprovalsReviewer `json:"approvalsReviewer,omitempty,omitzero"`

	// Replacement base instructions applied to the resumed thread.
	BaseInstructions *string `json:"baseInstructions,omitempty,omitzero"`

	// Codex configuration overrides reconstructed for the resumed thread.
	Config *json.RawMessage `json:"config,omitempty,omitzero"`

	// Working directory applied when the thread is resumed.
	Cwd *string `json:"cwd,omitempty,omitzero"`

	// Developer instructions attached while resuming a thread.
	DeveloperInstructions *string `json:"developerInstructions,omitempty,omitzero"`

	// Turn identifiers omitted when loading the resumed thread.
	ExcludeTurns []string `json:"excludeTurns,omitempty,omitzero"`

	// Replacement conversation history supplied while resuming.
	History *json.RawMessage `json:"history,omitempty,omitzero"`

	// Pagination request controlling the initial resumed-turn page.
	InitialTurnsPage *json.RawMessage `json:"initialTurnsPage,omitempty,omitzero"`

	// Model override applied to the resumed thread.
	Model *string `json:"model,omitempty,omitzero"`

	// Model-provider override applied to the resumed thread.
	ModelProvider *string `json:"modelProvider,omitempty,omitzero"`

	// Filesystem path of the Codex rollout to resume.
	Path *string `json:"path,omitempty,omitzero"`

	// Named Codex permission-profile identifier applied to the resumed thread; it
	// cannot be combined with sandbox.
	Permissions *string `json:"permissions,omitempty,omitzero"`

	// Response personality override applied to the resumed thread.
	Personality *string `json:"personality,omitempty,omitzero"`

	// Replacement runtime workspace roots for the resumed thread; paths must be
	// absolute.
	RuntimeWorkspaceRoots []string `json:"runtimeWorkspaceRoots,omitempty,omitzero"`

	// Sandbox override applied while resuming the thread.
	Sandbox *OpenAIAgentOptionsThreadResumeSandbox `json:"sandbox,omitempty,omitzero"`

	// Processing tier override applied to the resumed thread.
	ServiceTier *string `json:"serviceTier,omitempty,omitzero"`

	// Codex thread identifier to resume.
	ThreadId *string `json:"threadId,omitempty,omitzero"`
}

// Parameters used to start a new Codex app-server thread.
type ThreadStart struct {
	// Whether Codex may fall back to a different provider model.
	AllowProviderModelFallback *bool `json:"allowProviderModelFallback,omitempty,omitzero"`

	// Codex command-approval policy for the thread.
	ApprovalPolicy *json.RawMessage `json:"approvalPolicy,omitempty,omitzero"`

	// Reviewer implementation used to evaluate approval requests.
	ApprovalsReviewer *OpenAIAgentOptionsThreadStartApprovalsReviewer `json:"approvalsReviewer,omitempty,omitzero"`

	// Replacement base instruction text for the Codex thread.
	BaseInstructions *string `json:"baseInstructions,omitempty,omitzero"`

	// Codex configuration overrides derived from Captain sandbox and caller-tool
	// settings.
	Config *json.RawMessage `json:"config,omitempty,omitzero"`

	// Initial working directory for the Codex thread.
	Cwd *string `json:"cwd,omitempty,omitzero"`

	// Initial Daybreak choice for a persistent Codex thread; not supported for
	// ephemeral threads.
	DaybreakEnabled *bool `json:"daybreakEnabled,omitempty,omitzero"`

	// Developer instruction text attached to the Codex thread.
	DeveloperInstructions *string `json:"developerInstructions,omitempty,omitzero"`

	// Tool definitions registered dynamically with the Codex thread.
	DynamicTools *json.RawMessage `json:"dynamicTools,omitempty,omitzero"`

	// Named execution environments available to the Codex thread.
	Environments *json.RawMessage `json:"environments,omitempty,omitzero"`

	// Whether Codex avoids persisting the thread to disk.
	Ephemeral *bool `json:"ephemeral,omitempty,omitzero"`

	// Whether raw protocol events are included in item streams.
	ExperimentalRawEvents *bool `json:"experimentalRawEvents,omitempty,omitzero"`

	// Codex policy controlling which history is retained.
	HistoryMode *string `json:"historyMode,omitempty,omitzero"`

	// Protocol test field reserved by the experimental app-server schema.
	MockExperimentalField *string `json:"mockExperimentalField,omitempty,omitzero"`

	// Model identifier used to start the Codex thread.
	Model *string `json:"model,omitempty,omitzero"`

	// Codex model-provider implementation selected for the thread.
	ModelProvider *string `json:"modelProvider,omitempty,omitzero"`

	// Codex multi-agent coordination mode for the thread.
	MultiAgentMode *string `json:"multiAgentMode,omitempty,omitzero"`

	// Named Codex permission-profile identifier for the thread; it cannot be combined
	// with sandbox.
	Permissions *string `json:"permissions,omitempty,omitzero"`

	// Named Codex response personality for the thread.
	Personality *string `json:"personality,omitempty,omitzero"`

	// Codex project identifier associated with the thread.
	ProjectId *string `json:"projectId,omitempty,omitzero"`

	// Replacement runtime workspace roots for the Codex thread; paths must be
	// absolute.
	RuntimeWorkspaceRoots []string `json:"runtimeWorkspaceRoots,omitempty,omitzero"`

	// Named Codex sandbox mode for the thread.
	Sandbox *OpenAIAgentOptionsThreadStartSandbox `json:"sandbox,omitempty,omitzero"`

	// Filesystem roots selected for capability discovery.
	SelectedCapabilityRoots []string `json:"selectedCapabilityRoots,omitempty,omitzero"`

	// Service identity attached to the Codex thread.
	ServiceName *string `json:"serviceName,omitempty,omitzero"`

	// Processing tier selected for the Codex thread.
	ServiceTier *string `json:"serviceTier,omitempty,omitzero"`

	// Source label describing how the session was launched.
	SessionStartSource *string `json:"sessionStartSource,omitempty,omitzero"`

	// Native source label attached to the Codex thread.
	ThreadSource *string `json:"threadSource,omitempty,omitzero"`
}

// Parameters used to start a turn on an active Codex app-server thread.
type TurnStart struct {
	// Extra context attached to the turn outside the user input list.
	AdditionalContext *string `json:"additionalContext,omitempty,omitzero"`

	// Approval-policy override for the turn.
	ApprovalPolicy *json.RawMessage `json:"approvalPolicy,omitempty,omitzero"`

	// Reviewer override used for approvals in this turn.
	ApprovalsReviewer *OpenAIAgentOptionsTurnStartApprovalsReviewer `json:"approvalsReviewer,omitempty,omitzero"`

	// Client-assigned identifier for the turn's user message.
	ClientUserMessageId *string `json:"clientUserMessageId,omitempty,omitzero"`

	// Codex collaboration mode applied for the turn.
	CollaborationMode *json.RawMessage `json:"collaborationMode,omitempty,omitzero"`

	// Working-directory override for the turn.
	Cwd *string `json:"cwd,omitempty,omitzero"`

	// Codex cyber-access program configuration for the turn.
	CyberAccessProgram *json.RawMessage `json:"cyberAccessProgram,omitempty,omitzero"`

	// Replacement list of plugin identifiers disabled for the thread; an empty list
	// clears it.
	DisabledPluginIds []string `json:"disabledPluginIds,omitempty,omitzero"`

	// Reasoning effort used for this Codex turn.
	Effort *string `json:"effort,omitempty,omitzero"`

	// Execution environments made available for this turn.
	Environments *json.RawMessage `json:"environments,omitempty,omitzero"`

	// Text and local-image items supplied for the Codex turn.
	Input *json.RawMessage `json:"input,omitempty,omitzero"`

	// Model identifier used for this Codex turn.
	Model *string `json:"model,omitempty,omitzero"`

	// Codex multi-agent coordination mode for this turn.
	MultiAgentMode *string `json:"multiAgentMode,omitempty,omitzero"`

	// JSON Schema constraining the final turn response.
	OutputSchema *json.RawMessage `json:"outputSchema,omitempty,omitzero"`

	// Named Codex permission-profile identifier for this turn and subsequent turns;
	// it cannot be combined with sandboxPolicy.
	Permissions *string `json:"permissions,omitempty,omitzero"`

	// Response personality override for this turn.
	Personality *string `json:"personality,omitempty,omitzero"`

	// Client metadata forwarded to the underlying Responses API call.
	ResponsesapiClientMetadata *json.RawMessage `json:"responsesapiClientMetadata,omitempty,omitzero"`

	// Replacement runtime workspace roots for this turn and subsequent turns; paths
	// must be absolute.
	RuntimeWorkspaceRoots []string `json:"runtimeWorkspaceRoots,omitempty,omitzero"`

	// Detailed sandbox policy override for this turn.
	SandboxPolicy *json.RawMessage `json:"sandboxPolicy,omitempty,omitzero"`

	// Processing tier selected for this turn.
	ServiceTier *string `json:"serviceTier,omitempty,omitzero"`

	// Whether a service tier applies only to this turn.
	ServiceTierForTurn *bool `json:"serviceTierForTurn,omitempty,omitzero"`

	// Reasoning-summary mode requested for the turn.
	Summary *string `json:"summary,omitempty,omitzero"`

	// Active Codex thread receiving the turn.
	ThreadId *string `json:"threadId,omitempty,omitzero"`

	// Out-of-band tool output supplied with the turn-start request.
	ToolOutput *json.RawMessage `json:"toolOutput,omitempty,omitzero"`

	// Source describing what triggered the Codex turn.
	TurnTrigger *string `json:"turnTrigger,omitempty,omitzero"`
}
