// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package adapters

import "encoding/json"

// Native DeepSeek Chat Completions request options used by Captain's
// OpenAI-compatible API runtime.
type DeepSeekAPIOptions struct {
	// Deprecated penalty based on how frequently a token has appeared.
	FrequencyPenalty *float64 `json:"frequency_penalty,omitempty,omitzero"`

	// Whether token log probabilities are included in the response.
	Logprobs *bool `json:"logprobs,omitempty,omitzero"`

	// Maximum number of tokens generated in the completion.
	MaxTokens *int `json:"max_tokens,omitempty,omitzero"`

	// Conversation messages and tool results sent to DeepSeek.
	Messages json.RawMessage `json:"messages"`

	// DeepSeek chat or reasoner model identifier.
	Model DeepSeekAPIOptionsModel `json:"model"`

	// Deprecated penalty based on whether a token has appeared.
	PresencePenalty *float64 `json:"presence_penalty,omitempty,omitzero"`

	// Relative reasoning effort requested from supported DeepSeek models.
	ReasoningEffort *DeepSeekAPIOptionsReasoningEffort `json:"reasoning_effort,omitempty,omitzero"`

	// Plain-text or JSON-object response format.
	ResponseFormat *json.RawMessage `json:"response_format,omitempty,omitzero"`

	// One or more text sequences that stop token generation.
	Stop *json.RawMessage `json:"stop,omitempty,omitzero"`

	// Whether the completion is returned as server-sent streaming events.
	Stream *bool `json:"stream,omitempty,omitzero"`

	// Additional behavior such as including a final usage chunk in the stream.
	StreamOptions *json.RawMessage `json:"stream_options,omitempty,omitzero"`

	// Sampling temperature between zero and two.
	Temperature *float64 `json:"temperature,omitempty,omitzero"`

	// Whether DeepSeek thinking mode is enabled for the request.
	Thinking *json.RawMessage `json:"thinking,omitempty,omitzero"`

	// Policy selecting whether and which function tool the model may call.
	ToolChoice *json.RawMessage `json:"tool_choice,omitempty,omitzero"`

	// Function tool definitions derived from Captain caller tools.
	Tools *json.RawMessage `json:"tools,omitempty,omitzero"`

	// Number of likely tokens returned with log probabilities at each position.
	TopLogprobs *int `json:"top_logprobs,omitempty,omitzero"`

	// Cumulative probability mass retained during nucleus sampling.
	TopP *float64 `json:"top_p,omitempty,omitzero"`

	// Stable end-user identifier used by DeepSeek for abuse detection.
	UserId *string `json:"user_id,omitempty,omitzero"`
}

type DeepSeekAPIOptionsModel string

const DeepSeekAPIOptionsModelDeepseekChat DeepSeekAPIOptionsModel = "deepseek-chat"
const DeepSeekAPIOptionsModelDeepseekReasoner DeepSeekAPIOptionsModel = "deepseek-reasoner"

type DeepSeekAPIOptionsReasoningEffort string

const DeepSeekAPIOptionsReasoningEffortHigh DeepSeekAPIOptionsReasoningEffort = "high"
const DeepSeekAPIOptionsReasoningEffortLow DeepSeekAPIOptionsReasoningEffort = "low"
const DeepSeekAPIOptionsReasoningEffortMax DeepSeekAPIOptionsReasoningEffort = "max"
const DeepSeekAPIOptionsReasoningEffortMedium DeepSeekAPIOptionsReasoningEffort = "medium"
const DeepSeekAPIOptionsReasoningEffortXhigh DeepSeekAPIOptionsReasoningEffort = "xhigh"
