package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"sync"
	"time"

	"github.com/flanksource/captain/pkg/ai"
	"github.com/flanksource/captain/pkg/api"
	clickyrpc "github.com/flanksource/clicky/rpc"
	"github.com/spf13/cobra"
)

// AttachPromptSchemaFlag adds `captain prompt --schema` to the generated prompt
// entity root. The prompt command itself is generated by clicky.GenerateCLI, so
// this hook wraps the generated list RunE after registration.
func AttachPromptSchemaFlag(root *cobra.Command) error {
	promptCmd, _, err := root.Find([]string{"prompt"})
	if err != nil {
		return fmt.Errorf("find prompt command: %w", err)
	}
	if promptCmd == nil || promptCmd.Name() != "prompt" {
		return fmt.Errorf("find prompt command: got %v", promptCmd)
	}

	var schema bool
	promptCmd.Flags().BoolVar(&schema, "schema", false, "Print prompt/spec editor JSON schemas and exit")
	originalArgs := promptCmd.Args
	originalRunE := promptCmd.RunE
	promptCmd.Args = func(cmd *cobra.Command, args []string) error {
		if schema {
			if len(args) > 0 {
				return fmt.Errorf("--schema takes no positional arguments (got %v)", args)
			}
			return nil
		}
		if originalArgs != nil {
			return originalArgs(cmd, args)
		}
		return nil
	}
	promptCmd.RunE = func(cmd *cobra.Command, args []string) error {
		if schema {
			return WritePromptSchema(cmd.OutOrStdout())
		}
		if originalRunE != nil {
			return originalRunE(cmd, args)
		}
		return cmd.Help()
	}
	return nil
}

func WritePromptSchema(w io.Writer) error {
	doc, err := PromptSchemaDocument()
	if err != nil {
		return err
	}
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	return enc.Encode(doc)
}

// PromptSchemaDocument assembles the prompt/spec editor schema document from the
// live runtime: the cmux "extra args" reflected from Go structs (cached, since
// they never change within a process) and the available backends/models probed
// from the environment (ai.CachedAdapters owns the short-TTL cache so a
// long-running serve process reflects key/model changes without re-probing per
// request).
func PromptSchemaDocument() (map[string]any, error) {
	adapters, err := schemaAdapters()
	if err != nil {
		return nil, err
	}
	return buildPromptSchemaDocument(adapters)
}

// schemaAdapters sources the probed adapters through pkg/ai's cache. It is a
// package var so tests can substitute a deterministic, network-free stub.
var schemaAdapters = func() ([]AdapterStatus, error) {
	return ai.CachedAdapters(time.Now())
}

// reflectedSchemaBytes holds the JSON of the reflection-derived schemas. They are
// process-immutable, so they are reflected once and re-parsed into a fresh map
// per document (parsing yields an independent copy that conditional injection can
// mutate without corrupting the cache).
type reflectedSchemaBytes struct {
	spec         []byte
	prompt       []byte
	promptAction []byte
	args         map[api.Backend][]byte // per-backend cmux "extra args" schema
}

var reflectedSchemas = sync.OnceValues(func() (reflectedSchemaBytes, error) {
	spec, err := json.Marshal(api.Schema(&api.Spec{}))
	if err != nil {
		return reflectedSchemaBytes{}, fmt.Errorf("reflect spec schema: %w", err)
	}
	prompt, err := json.Marshal(api.Schema(&api.Prompt{}))
	if err != nil {
		return reflectedSchemaBytes{}, fmt.Errorf("reflect prompt schema: %w", err)
	}
	action, err := json.Marshal(clickyrpc.SchemaForStruct(PromptActionFlags{}))
	if err != nil {
		return reflectedSchemaBytes{}, fmt.Errorf("reflect promptAction schema: %w", err)
	}
	args, err := backendArgSchemasJSON()
	if err != nil {
		return reflectedSchemaBytes{}, err
	}
	return reflectedSchemaBytes{spec: spec, prompt: prompt, promptAction: action, args: args}, nil
})

// promptSchemaExampleSpec is a portable, self-consistent example: no machine paths,
// a model resolved from the catalog default, and cliArgs that only use fields the
// selected backend (claude-cmux) actually accepts.
func promptSchemaExampleSpec() map[string]any {
	return map[string]any{
		"model":       exampleModelName(),
		"backend":     string(api.BackendClaudeCmux),
		"effort":      string(api.EffortMedium),
		"temperature": 0.2,
		"noCache":     true,
		"prompt": map[string]any{
			"user":         "Update the prompt runtime editor and keep the payload compact.",
			"system":       "Answer with direct implementation guidance.",
			"appendSystem": "Prefer existing clicky-ui primitives.",
		},
		"budget": map[string]any{
			"cost":      0.5,
			"maxTokens": 8000,
			"maxTurns":  6,
			"timeout":   "30m",
		},
		"permissions": map[string]any{
			"mode":    string(api.PermissionAcceptEdits),
			"presets": []string{string(api.PresetEdit)},
			"tools": map[string]any{
				"Read": "allow",
				"Edit": "ask",
				"Bash": "deny",
			},
			"mcp": map[string]any{
				"filesystem": "enabled",
				"gavel":      "disabled",
			},
			"plugins": map[string]any{
				".claude/plugins/example": "disabled",
			},
			"skills": map[string]any{
				".agents/skills/example-skill": "enabled",
			},
		},
		"memory": map[string]any{
			"skipHooks": true,
			"skills":    []string{".agents/skills/example-skill"},
		},
		"setup": map[string]any{
			"cwd":     ".",
			"baseDir": ".shell",
			"dotenv":  []string{".env", ".env.local"},
			"envVars": []map[string]any{
				{"name": "CAPTAIN_RUNTIME", "value": "storybook"},
				{"name": "GAVEL_PROFILE", "value": "local"},
			},
		},
		"cliArgs": map[string]any{
			"addDir":    []string{"packages/ui"},
			"mcpConfig": []string{"./mcp.json"},
		},
	}
}

// exampleModelName resolves the catalog default to the bare model slug used in the
// spec's `model` field (e.g. "claude-sonnet-5"), falling back to the raw id.
func exampleModelName() string {
	m, err := ai.LookupModel(ai.DefaultModelID)
	if err != nil {
		return ai.DefaultModelID
	}
	return m.BareID()
}
